version: "3.3"

# Web-UI is Defined by Local "Dockerfile", Must Be Rebuilt Each Time
services:
  stanleyfailserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8888:80
    restart: always
